// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl2OPOYZEsEnAziQ1Oi0ku_CqEmG8FD20',
    appId: '1:1060918976348:web:e4ef76f0da741e5dc5eb99',
    messagingSenderId: '1060918976348',
    projectId: 'sakeny-40c01',
    authDomain: 'sakeny-40c01.firebaseapp.com',
    storageBucket: 'sakeny-40c01.appspot.com',
    measurementId: 'G-FW3RX3NVDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBthz6PPxMeyTtQjN6RmAPYzmZ_lz_vVW0',
    appId: '1:1060918976348:android:937565162dc51134c5eb99',
    messagingSenderId: '1060918976348',
    projectId: 'sakeny-40c01',
    storageBucket: 'sakeny-40c01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT61-6MLmC_N8swTa02TwbEo9f1uTBE0w',
    appId: '1:1060918976348:ios:70dfbdf15baa1a62c5eb99',
    messagingSenderId: '1060918976348',
    projectId: 'sakeny-40c01',
    storageBucket: 'sakeny-40c01.appspot.com',
    androidClientId: '1060918976348-4ajhn7759tse2psikkj4nnti3vvev6ub.apps.googleusercontent.com',
    iosClientId: '1060918976348-2ac481umd1uqbun6hd5tb22j2vd9o1af.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakenyOwners',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT61-6MLmC_N8swTa02TwbEo9f1uTBE0w',
    appId: '1:1060918976348:ios:4deb6482bf75121ec5eb99',
    messagingSenderId: '1060918976348',
    projectId: 'sakeny-40c01',
    storageBucket: 'sakeny-40c01.appspot.com',
    androidClientId: '1060918976348-4ajhn7759tse2psikkj4nnti3vvev6ub.apps.googleusercontent.com',
    iosClientId: '1060918976348-ubh1502v0p5ipinl42q9o7as3r088ohl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakenyOwners.RunnerTests',
  );
}
